# Generated by Django 6.0.4 on 2026-04-25 18:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_id', models.CharField(max_length=20, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=32748)),
                ('elevation', models.FloatField(null=True)),
                ('distance_to_river', models.FloatField(null=True)),
                ('water_depth', models.FloatField(default=0.0)),
            ],
        ),
    ]
