# Generated by Django 6.0.4 on 2026-04-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gridcell',
            name='water_depth',
        ),
    ]
